# Generated by Django 6.0.3 on 2026-04-03 19:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('calorias_por_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('proteinas_por_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('carbohidratos_por_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('grasas_por_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comodidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url_icono', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url_video_demostracion', models.URLField(blank=True, null=True)),
                ('url_imagen_demostracion', models.URLField(blank=True, null=True)),
                ('tipo_fuerza', models.CharField(blank=True, max_length=50, null=True)),
                ('dificultad', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plan', models.CharField(max_length=100, unique=True)),
                ('precio_inscripcion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_mensualidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion_plan', models.TextField()),
                ('incluye_alimentacion', models.BooleanField(default=False)),
                ('incluye_entrenamiento_personalizado', models.BooleanField(default=False)),
                ('acceso_todas_sedes', models.BooleanField(default=False)),
                ('incluye_estacionamiento', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sede', models.CharField(max_length=100, unique=True)),
                ('direccion', models.TextField()),
                ('horario_lunes_viernes_apertura', models.TimeField()),
                ('horario_lunes_viernes_cierre', models.TimeField()),
                ('horario_sabado_apertura', models.TimeField()),
                ('horario_sabado_cierre', models.TimeField()),
                ('horario_domingo_apertura', models.TimeField()),
                ('horario_domingo_cierre', models.TimeField()),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('link_whatsapp_chat', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url_icono', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('firebase_uid', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('cedula_identidad', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('Papeado', 'Papeado'), ('Papeada', 'Papeada')], max_length=10, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estatura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('url_foto_perfil', models.URLField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('id_sede_preferida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sede')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('min_estatura_cm', models.IntegerField(blank=True, null=True)),
                ('max_estatura_cm', models.IntegerField(blank=True, null=True)),
                ('min_peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_edad', models.IntegerField(blank=True, null=True)),
                ('max_edad', models.IntegerField(blank=True, null=True)),
                ('tipo_dieta', models.CharField(blank=True, max_length=50, null=True)),
                ('id_creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DietaAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_gramos', models.DecimalField(decimal_places=2, max_digits=6)),
                ('momento_dia', models.CharField(max_length=50)),
                ('orden', models.IntegerField()),
                ('id_alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alimento')),
                ('id_dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dieta')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('Inscripcion', 'Inscripcion'), ('Mensualidad', 'Mensualidad')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('Pago movil', 'Pago movil'), ('Zelle', 'Zelle'), ('Efectivo', 'Efectivo')], max_length=20)),
                ('numero_referencia', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('monto_efectivo_divisa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('codigo_unico_confirmacion', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('estado_pago', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_administrador_verificador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_verificados', to=settings.AUTH_USER_MODEL)),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_identidad', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado_pre_inscripcion', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('Convertida_a_Usuario', 'Convertida_a_Usuario')], default='Pendiente', max_length=30)),
                ('id_administrador_gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_pago_inscripcion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pago')),
                ('id_plan_interes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RutinaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField(blank=True, null=True)),
                ('repeticiones', models.CharField(blank=True, max_length=50, null=True)),
                ('descanso_segundos', models.IntegerField(blank=True, null=True)),
                ('orden', models.IntegerField()),
                ('id_ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ejercicio')),
                ('id_rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rutina')),
            ],
        ),
        migrations.CreateModel(
            name='GaleriaSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagen', models.URLField()),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('id_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galerias', to='core.sede')),
            ],
        ),
        migrations.CreateModel(
            name='SedeComodidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_comodidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comodidad')),
                ('id_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sede')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('texto_testimonio', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioDieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('id_dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dieta')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_plan', models.DateField()),
                ('fecha_fin_plan', models.DateField()),
                ('fecha_pago_inscripcion', models.DateField(blank=True, null=True)),
                ('estado_plan', models.CharField(choices=[('Activo', 'Activo'), ('Vencido', 'Vencido'), ('Suspendido', 'Suspendido')], default='Activo', max_length=20)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.plan')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rol')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='roles_sistema',
            field=models.ManyToManyField(related_name='usuarios', through='core.UsuarioRol', to='core.rol'),
        ),
        migrations.CreateModel(
            name='UsuarioRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('id_rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rutina')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
