# Generated by Django 6.0.3 on 2026-04-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='banco_origen',
            field=models.CharField(blank=True, choices=[('0102', '0102 - Banco de Venezuela'), ('0104', '0104 - Banco Venezolano de Crédito'), ('0105', '0105 - Banco Mercantil'), ('0108', '0108 - BBVA Provincial'), ('0114', '0114 - Bancaribe'), ('0115', '0115 - Banco Exterior'), ('0128', '0128 - Banco Caronf'), ('0134', '0134 - Banesco'), ('0137', '0137 - Banco Sofitasa'), ('0138', '0138 - Banco Plaza'), ('0151', '0151 - BFC Banco Fondo Común'), ('0156', '0156 - 100% Banco'), ('0157', '0157 - Delsur Banco Universal'), ('0163', '0163 - Banco del Tesoro'), ('0166', '0166 - Banco Agrícola'), ('0168', '0168 - Bancrecer'), ('0171', '0171 - Banco Activo'), ('0172', '0172 - Bancamiga'), ('0174', '0174 - Banplus'), ('0175', '0175 - Banco Digital de los Trabajadores'), ('0177', '0177 - BANFANB'), ('0191', '0191 - BNC')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='telefono_origen',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='ultimos_6_digitos_ref',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='codigo_unico_confirmacion',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('Pago movil', 'Pago movil'), ('Zelle', 'Zelle'), ('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia')], max_length=20),
        ),
    ]
