# Generated by Django 6.0.3 on 2026-04-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_pago_banco_telefono_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='incluye_lockers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='incluye_pases_web',
            field=models.BooleanField(default=False),
        ),
    ]
